# webサーバーの設定
webserver:

  # wordpressのイメージを取得。ローカルにないので、DockerHubから4.9.8-php7.0-apacheを指定して取得
  image: wordpress:4.9.8-php7.0-apache

  # 80番ポートに転送 ホストポート：コンテナポート
  ports:
   - "80:80"

  # 別コンテナのエイリアスを設定 （リンク）
  links:
   - "dbserver:mysql"


# dbサーバーの設定
dbserver:

  # mysqlのイメージを取得
  image: mysql:5.6

  # データのマウント先を指定 （先ほど作成したdataonlyコンテナ）
  volumes_from:
   - dataonly

  # 環境変数
  environment:
   MYSQL_ROOT_PASSWORD: password